# This file is used to mount graphdb docker and populate it 
# first with the files contained in import, and then 
# by executing the queries contained in queries.

version: "3"

services:
  graphdb:
    container_name: graphdb-preload
    # image: ontotext/graphdb:${GRAPHDB_VERSION}-ee
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        version: ${GRAPHDB_VERSION}

    # Load all files from ../import in repo defined in ./graphdb-repo-config.ttl
    
    entrypoint: [ "/bin/bash", "-c", "/opt/bin/preload.sh" ]

    # Preload given file to existing repository (here "demo")
    # entrypoint: [ "/opt/graphdb/dist/bin/preload", "preload", "-f", "-i", "demo", "/root/graphdb-import" ]

    environment: 
      REPOSITORY_ID: ${REPOSITORY_ID}
      GDB_JAVA_OPTS: >-
        -Xmx${GRAPHDB_HEAP_SIZE} -Xms${GRAPHDB_HEAP_SIZE}
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    volumes:
      # Change folders in the .env file
      - ${GRAPHDB_HOME}:/opt/graphdb/home
      - ${BIN_FOLDER}:/opt/bin
      - ${IMPORT_FOLDER}:/opt/graphdb/home/graphdb-import
      - ${QUERIES_FOLDER}:/opt/graphdb/home/graphdb-queries
      - ${REPOSITORY_CONFIG_FILE}:/opt/graphdb/repository_template.ttl
      - ${DATASET_FILE}:/opt/graphdb/DATASET.ttl
